### PR TITLE
Email Requesting + Data Access Implementation

### PR DESCRIPTION
**Pull request by cyltaracai**
1. Implement email requesting feature
2. Implement the data access package that is highly relevant to this feature. 
3. Fix related bugs in entities class

### CODE REVIEW

**Review by MacroSony — APPROVED** [review]
Great Work

**Comment by cyltaracai** [comment]
I reviewed my work a couple of days. With the last commit and push [c28e35c], the code is in a good shape for reviewing. Please review my code. Thank you

**Review by MacroSony — APPROVED** [review]
Great Work

**Review by ShuHaoLin2002 — APPROVED** [review]
no problems found

**Review by RitatataVan — APPROVED** [review]

**Pull request merged**
